[package]
name = "svid2usb"
description = "OBS Studio source plugin for the StarTech SVID2USB232 capture cable"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]
test = false
doctest = false

[dependencies]
em28281.workspace = true

[lints]
workspace = true
